### PR TITLE
Add additional shift bindings

### PR DESCRIPTION
**Pull request by tomgroenwoldt**
Hey! I'm looking forward to use your widget for terminal text editors :)

There were some shift bindings missing and this PR adds them. Though, I'm not sure if I caught all of them.

Thanks for this!

### CODE REVIEW

**Comment by Harzu** [comment]
@tomgroenwoldt Hey! this is basic bindings. You can use your own bindings for expanding base bindings or overwriting them (see more in [example](https://github.com/Harzu/iced_term/blob/master/examples/custom_bindings/src/main.rs))

**Comment by Harzu** [comment]
and also, as I can understand these bindings are just `shift + any character key` but this case is already [handled](https://github.com/Harzu/iced_term/blob/master/src/view.rs#L322) by default.

**Comment by tomgroenwoldt** [comment]
I was testing the `full_screen` example on `master`. Without my changes I wasn't able to type capitalized characters. Are you able to use `shift + any character key` in this example?

**Comment by Harzu** [comment]
> Thank you for the fast reply! :) I was testing the `full_screen` example on `master`. Without my changes I wasn't able to type capitalized characters. Are you able to use `shift + any character key` in this example?

Yep I run `full_screen` example and checked it. this feature is worked

Could you please explain to me more about your environment because I tested it on macos, linux (x11, wayland) and everywhere `shift + key` worked correctly

**Comment by tomgroenwoldt** [comment]
I run archlinux on wayland with kitty and also tested with alacritty. In both cases, I can't use `shift + key`, it results in `key` only.

**Comment by tomgroenwoldt** [comment]
Okay I see, thanks for your help! :)

**Pull request closed without merging**
